using System.Threading;

namespace pefi.http.OpenApiClientGenerator.Tests
{
    /// <summary>
    /// Comprehensive tests for <see cref="ClientGenerator"/>.
    /// Each test uses a focused, inline OpenAPI spec so that it validates a specific feature
    /// of the code-generation logic without depending on external files.
    /// </summary>
    public class ClientGeneratorTests
    {
        // ---------------------------------------------------------------------------
        // Helpers
        // ---------------------------------------------------------------------------

        private static Task<string?> Execute(string spec,
            string nameSpace = "MyNamespace",
            string className = "MyClient") =>
            ClientGenerator.Execute(nameSpace, className, spec, CancellationToken.None);

        private static string MinimalSpec(string paths = "", string schemas = "") =>
            $$"""
            {
              "openapi": "3.0.1",
              "info": { "title": "Test API", "version": "1.0" },
              "paths": { {{paths}} },
              "components": { "schemas": { {{schemas}} } }
            }
            """;

        // ---------------------------------------------------------------------------
        // Namespace and class
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_EmitsConfiguredNamespace()
        {
            var source = await Execute(MinimalSpec(), nameSpace: "Acme.Client");
            Assert.Contains("namespace Acme.Client", source);
        }

        [Fact]
        public async Task Execute_EmitsConfiguredClassName()
        {
            var source = await Execute(MinimalSpec(), className: "WidgetClient");
            Assert.Contains("public partial class WidgetClient", source);
        }

        [Fact]
        public async Task Execute_EmitsConstructorWithHttpClient()
        {
            var source = await Execute(MinimalSpec(), className: "WidgetClient");
            Assert.Contains("public WidgetClient(HttpClient httpClient)", source);
        }

        [Fact]
        public async Task Execute_EmitsAutoGeneratedHeader()
        {
            var source = await Execute(MinimalSpec());
            Assert.Contains("// <auto-generated/>", source);
        }

        [Fact]
        public async Task Execute_EmitsRequiredUsingStatements()
        {
            var source = await Execute(MinimalSpec());
            Assert.Contains("using System.Net.Http;", source);
            Assert.Contains("using System.Threading.Tasks;", source);
            Assert.Contains("using System.Text.Json;", source);
        }

        // ---------------------------------------------------------------------------
        // Model generation
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesModelClass_FromComponentsSchemas()
        {
            var schemas = """
                "Widget": {
                  "type": "object",
                  "properties": {
                    "name": { "type": "string" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public class Widget", source);
        }

        [Fact]
        public async Task Execute_GeneratesMultipleModelClasses()
        {
            var schemas = """
                "Alpha": { "type": "object", "properties": {} },
                "Beta":  { "type": "object", "properties": {} }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public class Alpha", source);
            Assert.Contains("public class Beta", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_String()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "label": { "type": "string" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public string label", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_NullableString()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "label": { "type": "string", "nullable": true }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public string? label", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Integer()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "count": { "type": "integer", "format": "int32" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public int count", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Long()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "bigNumber": { "type": "integer", "format": "int64" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public long bigNumber", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Boolean()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "active": { "type": "boolean" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public bool active", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Decimal()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "price": { "type": "number" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public decimal price", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Float()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "ratio": { "type": "number", "format": "float" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public float ratio", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Double()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "precision": { "type": "number", "format": "double" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public double precision", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_DateTimeOffset()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "createdAt": { "type": "string", "format": "date-time" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public DateTimeOffset createdAt", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_DateOnly()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "birthday": { "type": "string", "format": "date" }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public DateOnly birthday", source);
        }

        [Fact]
        public async Task Execute_GeneratesModelProperty_Array()
        {
            var schemas = """
                "Item": {
                  "type": "object",
                  "properties": {
                    "tags": { "type": "array", "items": { "type": "string" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public IReadOnlyList<string> tags", source);
        }

        // ---------------------------------------------------------------------------
        // API method generation
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesGetMethod()
        {
            var paths = """
                "/items": {
                  "get": {
                    "operationId": "ListItems",
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("ListItemsAsync(", source);
            Assert.Contains("HttpMethod.Get", source);
        }

        [Fact]
        public async Task Execute_GeneratesPostMethod()
        {
            var paths = """
                "/items": {
                  "post": {
                    "operationId": "CreateItem",
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("CreateItemAsync(", source);
            Assert.Contains("HttpMethod.Post", source);
        }

        [Fact]
        public async Task Execute_GeneratesDeleteMethod()
        {
            var paths = """
                "/items/{id}": {
                  "delete": {
                    "operationId": "DeleteItem",
                    "parameters": [
                      { "name": "id", "in": "path", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("DeleteItemAsync(", source);
            Assert.Contains("HttpMethod.Delete", source);
        }

        [Fact]
        public async Task Execute_GeneratesPutMethod()
        {
            var paths = """
                "/items/{id}": {
                  "put": {
                    "operationId": "UpdateItem",
                    "parameters": [
                      { "name": "id", "in": "path", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("UpdateItemAsync(", source);
            Assert.Contains("HttpMethod.Put", source);
            Assert.DoesNotContain("HttpMethod.GetPut", source);
        }

        [Fact]
        public async Task Execute_GeneratesAsyncTaskReturn_WhenNoJsonResponse()
        {
            var paths = """
                "/ping": {
                  "get": {
                    "operationId": "Ping",
                    "responses": { "204": { "description": "No Content" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("public async Task PingAsync(", source);
        }

        [Fact]
        public async Task Execute_GeneratesTypedReturn_WhenJsonResponsePresent()
        {
            var paths = """
                "/items": {
                  "get": {
                    "operationId": "GetItems",
                    "responses": {
                      "200": {
                        "description": "OK",
                        "content": {
                          "application/json": {
                            "schema": { "type": "array", "items": { "type": "string" } }
                          }
                        }
                      }
                    }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("public async Task<IReadOnlyList<string>> GetItemsAsync(", source);
        }

        [Fact]
        public async Task Execute_GeneratesTypedReturn_ReferenceSchema()
        {
            var schemas = """
                "Widget": { "type": "object", "properties": {} }
            """;
            var paths = """
                "/widget": {
                  "get": {
                    "operationId": "GetWidget",
                    "responses": {
                      "200": {
                        "description": "OK",
                        "content": {
                          "application/json": {
                            "schema": { "$ref": "#/components/schemas/Widget" }
                          }
                        }
                      }
                    }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths, schemas: schemas));
            Assert.Contains("Task<Widget> GetWidgetAsync(", source);
        }

        // ---------------------------------------------------------------------------
        // Path parameters
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesPathParameter_InMethodSignature()
        {
            var paths = """
                "/items/{id}": {
                  "get": {
                    "operationId": "GetItem",
                    "parameters": [
                      { "name": "id", "in": "path", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("string id", source);
        }

        [Fact]
        public async Task Execute_InterpolatesPathParameter_InUrl()
        {
            var paths = """
                "/orders/{orderId}": {
                  "get": {
                    "operationId": "GetOrder",
                    "parameters": [
                      { "name": "orderId", "in": "path", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("{orderid}", source);
        }

        // ---------------------------------------------------------------------------
        // Query parameters
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesQueryParameter_InMethodSignature()
        {
            var paths = """
                "/search": {
                  "get": {
                    "operationId": "Search",
                    "parameters": [
                      { "name": "q", "in": "query", "required": false,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("string? q", source);
        }

        [Fact]
        public async Task Execute_GeneratesQueryStringBuilder_ForQueryParams()
        {
            var paths = """
                "/search": {
                  "get": {
                    "operationId": "Search",
                    "parameters": [
                      { "name": "q", "in": "query", "required": false,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("queryBuilder", source);
            Assert.Contains("Uri.EscapeDataString", source);
        }

        [Fact]
        public async Task Execute_RequiredQueryParameter_HasNoDefaultNull()
        {
            var paths = """
                "/search": {
                  "get": {
                    "operationId": "Search",
                    "parameters": [
                      { "name": "filter", "in": "query", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            // Required parameters must not carry a default "= null"
            Assert.DoesNotContain("string filter = null", source);
        }

        // ---------------------------------------------------------------------------
        // Header parameters
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesHeaderParameter_AddedToRequest()
        {
            var paths = """
                "/secure": {
                  "get": {
                    "operationId": "SecureGet",
                    "parameters": [
                      { "name": "X-Api-Key", "in": "header", "required": true,
                        "schema": { "type": "string" } }
                    ],
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("request.Headers.Add(\"X-Api-Key\"", source);
        }

        // ---------------------------------------------------------------------------
        // Request body
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesBodyParameter_ForPostWithRequestBody()
        {
            var schemas = """
                "CreateItemRequest": { "type": "object", "properties": {} }
            """;
            var paths = """
                "/items": {
                  "post": {
                    "operationId": "CreateItem",
                    "requestBody": {
                      "required": true,
                      "content": {
                        "application/json": {
                          "schema": { "$ref": "#/components/schemas/CreateItemRequest" }
                        }
                      }
                    },
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths, schemas: schemas));
            Assert.Contains("JsonSerializer.Serialize(body", source);
            Assert.Contains("application/json", source);
        }

        [Fact]
        public async Task Execute_BodyParameter_AppearsInMethodSignature()
        {
            var schemas = """
                "Payload": { "type": "object", "properties": {} }
            """;
            var paths = """
                "/submit": {
                  "post": {
                    "operationId": "Submit",
                    "requestBody": {
                      "required": true,
                      "content": {
                        "application/json": {
                          "schema": { "$ref": "#/components/schemas/Payload" }
                        }
                      }
                    },
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths, schemas: schemas));
            Assert.Contains("Payload body", source);
        }

        // ---------------------------------------------------------------------------
        // Identifier sanitization
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_SanitizesHyphenatedOperationId()
        {
            var paths = """
                "/items": {
                  "get": {
                    "operationId": "get-all-items",
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            // Hyphens are replaced with underscores
            Assert.Contains("get_all_itemsAsync(", source);
        }

        [Fact]
        public async Task Execute_SanitizesSchemaNameWithSpecialCharacters()
        {
            var schemas = """
                "my-model": { "type": "object", "properties": {} }
            """;
            var source = await Execute(MinimalSpec(schemas: schemas));
            Assert.Contains("public class my_model", source);
        }

        // ---------------------------------------------------------------------------
        // Response deserialization
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_GeneratesDeserializeCall_WhenReturnTypePresent()
        {
            var paths = """
                "/items": {
                  "get": {
                    "operationId": "GetItems",
                    "responses": {
                      "200": {
                        "description": "OK",
                        "content": {
                          "application/json": {
                            "schema": { "type": "array", "items": { "type": "string" } }
                          }
                        }
                      }
                    }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("DeserializeAsync", source);
        }

        [Fact]
        public async Task Execute_DoesNotGenerateDeserializeCall_WhenNoJsonResponse()
        {
            var paths = """
                "/ping": {
                  "delete": {
                    "operationId": "Ping",
                    "responses": { "204": { "description": "No Content" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.DoesNotContain("DeserializeAsync", source);
        }

        // ---------------------------------------------------------------------------
        // CancellationToken
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_EachApiMethod_HasCancellationTokenParameter()
        {
            var paths = """
                "/items": {
                  "get": {
                    "operationId": "GetItems",
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.Contains("CancellationToken cancellationToken = default", source);
        }

        // ---------------------------------------------------------------------------
        // Error handling
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_ThrowsInvalidOperationException_ForInvalidSpec()
        {
            await Assert.ThrowsAsync<InvalidOperationException>(
                () => ClientGenerator.Execute("NS", "C", "this is not valid JSON", CancellationToken.None));
        }

        // ---------------------------------------------------------------------------
        // Minimal / edge-case specs
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_SpecWithNoPaths_ReturnsValidSource()
        {
            var source = await Execute(MinimalSpec());
            Assert.NotNull(source);
            Assert.Contains("public partial class MyClient", source);
        }

        [Fact]
        public async Task Execute_SpecWithNoSchemas_ReturnsValidSource()
        {
            var paths = """
                "/ping": {
                  "get": {
                    "operationId": "Ping",
                    "responses": { "200": { "description": "OK" } }
                  }
                }
            """;
            var source = await Execute(MinimalSpec(paths: paths));
            Assert.NotNull(source);
            Assert.Contains("PingAsync", source);
        }

        // ---------------------------------------------------------------------------
        // Full spec integration (uses the checked-in service_mgr_openapi.json)
        // ---------------------------------------------------------------------------

        [Fact]
        public async Task Execute_FullSpec_GeneratesExpectedModels()
        {
            var specPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "client_config", "service_mgr_openapi.json");
            var spec = System.IO.File.ReadAllText(specPath);

            var source = await ClientGenerator.Execute("MyNS", "ServiceMgrClient", spec, CancellationToken.None);

            Assert.NotNull(source);
            Assert.Contains("public class WeatherForecast", source);
            Assert.Contains("public class SelfServeConfigurationModel", source);
            Assert.Contains("public class ConditionConfiguration", source);
        }

        [Fact]
        public async Task Execute_FullSpec_GeneratesExpectedMethods()
        {
            var specPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "client_config", "service_mgr_openapi.json");
            var spec = System.IO.File.ReadAllText(specPath);

            var source = await ClientGenerator.Execute("MyNS", "ServiceMgrClient", spec, CancellationToken.None);

            Assert.NotNull(source);
            Assert.Contains("Get_All_ConfigsAsync(", source);
            Assert.Contains("CreateConfigAsync(", source);
            Assert.Contains("GetWeatherForecastAsync(", source);
        }

        [Fact]
        public async Task Execute_FullSpec_WeatherForecast_HasDateOnlyProperty()
        {
            var specPath = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "client_config", "service_mgr_openapi.json");
            var spec = System.IO.File.ReadAllText(specPath);

            var source = await ClientGenerator.Execute("MyNS", "ServiceMgrClient", spec, CancellationToken.None);

            Assert.NotNull(source);
            Assert.Contains("public DateOnly date", source);
        }
    }
}
