using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace pefi.http;

[Generator]
public class OpenApiClientGenerator : IIncrementalGenerator
{
    private const string ApiResponseSource = """
        // <auto-generated/>
        #pragma warning disable
        using System;
        using System.Collections.Generic;

        namespace pefi.http
        {
            /// <summary>Represents a raw HTTP response from a generated API client.</summary>
            public class ApiResponse
            {
                /// <summary>The HTTP status code returned by the server.</summary>
                public int StatusCode { get; }

                /// <summary>All response headers (including content headers) as a flat string dictionary.</summary>
                public IReadOnlyDictionary<string, string> Headers { get; }

                /// <summary>The raw response body as a string.</summary>
                public string RawContent { get; }

                public ApiResponse(int statusCode, IReadOnlyDictionary<string, string> headers, string rawContent)
                {
                    StatusCode = statusCode;
                    Headers = headers;
                    RawContent = rawContent;
                }
            }

            /// <summary>Represents an HTTP response that also carries a deserialized body of type <typeparamref name="T"/>.</summary>
            public class ApiResponse<T> : ApiResponse
            {
                /// <summary>The deserialized body, or <c>default</c> when the response was not successful.</summary>
                public T? Body { get; }

                public ApiResponse(int statusCode, IReadOnlyDictionary<string, string> headers, string rawContent, T? body)
                    : base(statusCode, headers, rawContent)
                {
                    Body = body;
                }
            }
        }
        """;

    private const string GenerateHttpClientAttributeSource = """
        // <auto-generated/>
        #pragma warning disable
        using System;

        namespace pefi.http
        {
            /// <summary>
            /// Marks a partial class to have an OpenAPI HttpClient implementation generated from the specified OpenAPI spec file.
            /// The spec file should be included in the project as an AdditionalFiles item.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            public sealed class GenerateHttpClientAttribute : Attribute
            {
                /// <summary>
                /// Initializes a new instance of the <see cref="GenerateHttpClientAttribute"/> class.
                /// </summary>
                /// <param name="specFileName">The name of the OpenAPI specification file (e.g., "my-api.openapi.json").
                /// This should match the filename of an AdditionalFiles item in your project.</param>
                public GenerateHttpClientAttribute(string specFileName)
                {
                    SpecFileName = specFileName;
                }

                /// <summary>Gets the name of the OpenAPI specification file.</summary>
                public string SpecFileName { get; }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Always emit the ApiResponse wrapper types and the attribute so consuming projects can use them.
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ApiResponse.g.cs", SourceText.From(ApiResponseSource, Encoding.UTF8));
            ctx.AddSource("GenerateHttpClientAttribute.g.cs", SourceText.From(GenerateHttpClientAttributeSource, Encoding.UTF8));
        });

        // Find all classes with our attribute
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetClassSymbolForSourceGen(ctx))
            .Where(static m => m is not null);



        var specifications = context.AdditionalTextsProvider
                                .Select((text, token) => new FileDeets( text.Path, text.GetText(token)?.ToString() ?? "" ))
                                .Collect<FileDeets>();

        // Generate the source
        context.RegisterSourceOutput(provider.Combine(specifications), Execute);
    }

    private class FileDeets(string path, string contents)
    {
        public string FileName { get; } = Path.GetFileName(path);
        public string Contents { get; } = contents;
    };

    private static ClassDeclarationContext? GetClassSymbolForSourceGen(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = (INamedTypeSymbol?)context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (symbol?.GetAttributes().Any(ad =>
                ad.AttributeClass?.ToDisplayString() == "pefi.http.GenerateHttpClientAttribute") == true)
        {
            var attribute = symbol.GetAttributes().First(ad =>
                ad.AttributeClass?.ToDisplayString() == "pefi.http.GenerateHttpClientAttribute");

            var specUrl = attribute.ConstructorArguments[0].Value?.ToString();
      
            if (specUrl is not null)
            {
                return new ClassDeclarationContext(symbol, specUrl,  classDeclaration);
            }
        }

        return null;
    }

    private static async void Execute(SourceProductionContext context, (ClassDeclarationContext? Left, ImmutableArray<FileDeets> Right) args)
    {
        var (cdt, files) = args;
        if (cdt is null) return;
        try
        {
            var src = await ClientGenerator.Execute(
                nameSpace: cdt.Symbol.ContainingNamespace.ToDisplayString(),
                className: cdt.Symbol.Name,
                sourceUrl: files.Single(x => x.FileName == cdt.SpecUrl).Contents,
                context.CancellationToken);

            if (string.IsNullOrEmpty(src))
            {
                throw new Exception("No src was returned from client generator.");
            }

            context.AddSource($"{cdt.Symbol.Name}.g.cs", SourceText.From(src!, Encoding.UTF8));

            context.ReportDiagnostic(Diagnostic.Create(
               new DiagnosticDescriptor(
                   "OAC1000",
                   "OpenAPI Client Generation Succeeded",
                   $"Generated client {cdt.Symbol.Name} from {cdt.SpecUrl}",
                   "OpenApiClientGenerator",
                   DiagnosticSeverity.Info,
                   true),
               Location.None));
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "OAC1001",
                    "OpenAPI Client Generation Error",
                    $"Error generating client {cdt.Symbol.Name} from {cdt.SpecUrl}: {ex.Message}",
                    "OpenApiClientGenerator",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None));
        }
    }
}

